version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - SECRET_KEY=your-secret-key-here-change-in-production
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Add a database service for future expansion
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: fastapi_cicd
  #     POSTGRES_USER: fastapi_user
  #     POSTGRES_PASSWORD: fastapi_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

  # Add Redis for caching (optional)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

# volumes:
#   postgres_data:
